// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rofttquepajhryacfdyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZnR0cXVlcGFqaHJ5YWNmZHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTMxNzgsImV4cCI6MjA2OTQ2OTE3OH0.4lGnhwe-fTJ3aLuV8_RJ2HKp7uCYYiC0e_mdTfneqkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});